apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: staticroute-operator
spec:
  selector:
    matchLabels:
      name: staticroute-operator
  template:
    metadata:
      labels:
        name: staticroute-operator
    spec:
      serviceAccountName: staticroute-operator 
      hostNetwork: true
      containers:
      - name: staticroute-operator
        image: us.icr.io/huszty/staticroute:latest
        command:
          - staticroute-operator
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: OPERATOR_NAME
          value: "staticroute-operator"
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
