kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: staticroute-operator
subjects:
- kind: ServiceAccount
  namespace: default
  name: staticroute-operator
roleRef:
  kind: ClusterRole
  name: staticroute-operator
  apiGroup: rbac.authorization.k8s.io
